[project]
name = "UniversalIMG"
version = "1.3.0"
description = "Open & edit .img files for GTA III / VC / SA (+GUI)"
license = { text = "MIT" }
authors = [
    { name = "Nikita Denissov", email = "n.denissov@proton.me" }
]
readme = "README.md"
requires-python = ">=3.10,<3.14"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Desktop Environment",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License"
]

dependencies = [
    "html-table-parser-python3 (>=0.3.1,<0.4.0)",
]

[project.optional-dependencies]
gui = [
    "darkdetect (>=0.8.0,<0.9.0)",
    "kivymd (>=1.2.0,<2.0.0)",
    'kivy (>=2.3.1,<3.0.0)',
    'pillow (>9.5.0); python_version > "3.12"'
]

[project.urls]
Homepage = "https://libertycity.net/file/181749"
Repository = "https://github.com/ndenissov/UniversalIMG"

[project.scripts]
UniversalIMG = "pyimgedit.gui:run"

[tool.poetry]
packages = [{ include = "pyimgedit" }]
include = ["pyimgedit/icon.png"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
[dependency-groups]
dev = [
    "pyinstaller (>=6.21.0,<7.0.0)"
]
